services:
  backend:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    expose:
      - "3000"
    env_file: "./server/.env"
    networks:
      - public
      - backend
      - observability
    depends_on:
      - loki
      - grafana
      # - spaces
  frontend:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - "3500:3500"
    env_file: "./client/.env"
    networks: 
      - public
    depends_on:
      - backend
  # spaces:
  #   env_file: ./server/.env # for the database_url
  #   environment:
  #     - UPLOAD_PATH=/data/uploads
  #     - ALLOWED_ORIGINS=http://localhost:3000
  #   image: vividsystem/spaces:latest
  #   ports:
  #     - "6570:6570"
  #   networks:
  #     - backend
  #     - observability
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  prometheus:
    image: prom/prometheus:v2.47.0
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:11.0.0
    ports:
      - "3001:3000"
networks:
  observability:
    driver: bridge
  public:
  backend:
volumes:
  jusstudy_postgres_data:
  loki-data:
  grafana-data:
