services:
  backend:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    env_file: "./server/.env"
    environment:
      - GRAFANA_LOKI_HOST=http://loki:3100
      - BOT_HOST=http://emi:8000
      - NODE_ENV=production
    networks:
      - public
      - backend
      - observability
    depends_on:
      - loki
      - grafana
      - emi
  frontend:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - "8080:8080"
    env_file: "./client/.env"
    environment:
      - NODE_ENV=production
    networks: 
      - public
    depends_on:
      - backend
  emi:
    build: ./emi
    env_file: "./emi/.env"
    networks:
      - backend
  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability
  prometheus:
    image: prom/prometheus:v2.47.0
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - observability
  grafana:
    env_file: .env
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=info
      # use console and alloy to get console info
      - GF_LOG_MODE=console
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:11.0.0
    ports:
      - "3001:3000"
    networks:
      - observability
networks:
  observability:
    driver: bridge
  public:
  backend:
volumes:
  jusstudy_postgres_data:
  loki-data:
  grafana-data:
